### ISSUE TITLE
Making it work for normal MQTT TCP traffic ?

### ISSUE THREAD

**Issue by natcl** [labbsr0x/traefik-letsencrypt-mqtt#1]
Thanks to your example I was able to make my websocket mosquitto work, I was wondering if it would be possible to do the same for regular TCP MQTT traffic or perhaps it's impossible ?

**Comment by tiagostutz** [comment]
Hi @natcl ! That's great to know the example was helpful... Awesome.!

Unfortunately, **traefik** current doesn't support TCP traffic, just HTTP. To proxy/load-balance this TCP traffik we currently use HAProxy but we are planning to build another traefik-like solution, focused on Docker Container tags and things like that... sounds good?

**Comment by natcl** [comment]
Thanks alot for the answer will stop trying to make it work for now:)
Will watch this space for updates thanks !

**Comment by natcl** [comment]
Not sure if it's going to be helpful but traefik just added TCP support:
https://github.com/containous/traefik/pull/4587
